# Generated by Django 5.1.3 on 2024-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_correspondenceaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenceaddress',
            name='residentialAddressSame',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
