# Generated by Django 5.1.3 on 2024-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_correspondenceaddress_residentialaddresssame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='residentialAddressSame',
            field=models.BooleanField(default=True),
        ),
    ]
