# Generated by Django 5.1.3 on 2024-12-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_correspondenceaddress_residentialaddresssame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrySelected', models.CharField(max_length=100)),
                ('streetAddress', models.CharField(max_length=255)),
                ('localityOrVillage', models.CharField(max_length=255)),
                ('selectedState', models.CharField(max_length=100)),
                ('citySelected', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Residential Address',
                'verbose_name_plural': 'Residential Addresses',
            },
        ),
    ]
