# Generated by Django 5.1.3 on 2024-12-07 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_residentialaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetailsAppearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('10th Appearing', '10th Appearing'), ('12th Appearing', '12th Appearing')], max_length=20)),
                ('board', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=50)),
                ('subjects', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_details_appearing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Details Appearing',
                'verbose_name_plural': 'Education Details Appearing',
            },
        ),
    ]
