# Generated by Django 5.1.3 on 2024-12-07 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_educationdetailsappearing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetailsPassed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('12th Passed', '12th Passed')], max_length=20)),
                ('board', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=50)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subjects', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_details_passed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Details Passed',
                'verbose_name_plural': 'Education Details Passed',
            },
        ),
    ]
