# Generated by Django 5.1.3 on 2024-12-07 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_educationdetailspassed'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
